import { Component } from '@angular/core';
import { NavbarComponent } from '../../../templates/navbar/navbar.component';
import { Timestamp } from 'firebase/firestore';
import { Product } from '../../../models/product.model';
import { ProductCardComponent } from '../product-card/product-card.component';
@Component({
  selector: 'app-shop-home',
  standalone: true,
  imports: [NavbarComponent, ProductCardComponent],
  templateUrl: './shop-home.component.html',
  styleUrl: './shop-home.component.scss',
})
export class ShopHomeComponent {
  testProducts: Product[] = [
    {
      id: '1',
      name: 'Yoga Mat',
      colors: ['Blue', 'Green'],
      category: 'Yoga Equipment',
      quantity: 100,
      arrivalTime: '2023-08-01T08:30:00Z',
      brand: 'YogiPro',
      origin: 'India',
      quality: 'Premium',
      material: 'Natural Rubber',
      description: 'Eco-friendly yoga mat made from natural rubber.',
      promotion: '10% off for first-time buyers',
      price: 30.99,
      status: 'available',
      created_at: Timestamp.fromDate(new Date('2023-06-01')),
      updated_at: Timestamp.fromDate(new Date('2023-07-01')),
      path_to_image: 'path/to/yoga-mat.jpg',
    },
    {
      id: '2',
      name: 'Meditation Cushion',
      colors: ['Purple', 'Red'],
      category: 'Yoga Accessories',
      quantity: 50,
      arrivalTime: '2023-07-15T12:00:00Z',
      brand: 'ZenHome',
      origin: 'India',
      quality: 'High',
      material: 'Cotton',
      description: 'Comfortable cushion perfect for meditation.',
      promotion: '',
      price: 20.49,
      status: 'available',
      created_at: Timestamp.fromDate(new Date('2023-05-10')),
      updated_at: Timestamp.fromDate(new Date('2023-06-15')),
      path_to_image: 'path/to/meditation-cushion.jpg',
    },
    {
      id: '3',
      name: 'Pilates Ball',
      colors: ['Pink', 'Gray'],
      category: 'Fitness Equipment',
      quantity: 75,
      arrivalTime: '2023-09-01T10:00:00Z',
      brand: 'FitLife',
      origin: 'China',
      quality: 'Standard',
      material: 'PVC',
      description: 'Durable pilates ball for versatile workouts.',
      promotion: 'Free workout guide included',
      price: 15.99,
      status: 'available',
      created_at: Timestamp.fromDate(new Date('2023-06-10')),
      updated_at: Timestamp.fromDate(new Date('2023-07-20')),
      path_to_image: 'path/to/pilates-ball.jpg',
    },
    {
      id: '4',
      name: 'Resistance Bands',
      colors: ['Yellow', 'Black'],
      category: 'Fitness Accessories',
      quantity: 200,
      arrivalTime: '2023-07-20T11:00:00Z',
      brand: 'StrongFlex',
      origin: 'USA',
      quality: 'Premium',
      material: 'Latex',
      description: 'Set of resistance bands for strength training.',
      promotion: 'Buy one, get one 50% off',
      price: 25.99,
      status: 'available',
      created_at: Timestamp.fromDate(new Date('2023-05-15')),
      updated_at: Timestamp.fromDate(new Date('2023-06-25')),
      path_to_image: 'path/to/resistance-bands.jpg',
    },
    {
      id: '5',
      name: 'Foam Roller',
      colors: ['Black', 'Blue'],
      category: 'Recovery Equipment',
      quantity: 120,
      arrivalTime: '2023-08-05T09:00:00Z',
      brand: 'RecoveryPro',
      origin: 'USA',
      quality: 'High',
      material: 'EVA Foam',
      description: 'High-density foam roller for muscle recovery.',
      promotion: '',
      price: 18.99,
      status: 'available',
      created_at: Timestamp.fromDate(new Date('2023-05-20')),
      updated_at: Timestamp.fromDate(new Date('2023-06-30')),
      path_to_image: 'path/to/foam-roller.jpg',
    },
    {
      id: '6',
      name: 'Yoga Block',
      colors: ['Purple', 'Brown'],
      category: 'Yoga Accessories',
      quantity: 150,
      arrivalTime: '2023-07-25T13:00:00Z',
      brand: 'YogiPro',
      origin: 'India',
      quality: 'Standard',
      material: 'Cork',
      description: 'Lightweight cork yoga block for stability.',
      promotion: '15% off on orders over $50',
      price: 10.99,
      status: 'available',
      created_at: Timestamp.fromDate(new Date('2023-06-05')),
      updated_at: Timestamp.fromDate(new Date('2023-07-05')),
      path_to_image: 'path/to/yoga-block.jpg',
    },
    {
      id: '7',
      name: 'Exercise Mat',
      colors: ['Green', 'Gray'],
      category: 'Fitness Equipment',
      quantity: 90,
      arrivalTime: '2023-08-10T08:00:00Z',
      brand: 'FitLife',
      origin: 'China',
      quality: 'Premium',
      material: 'TPE',
      description: 'Non-slip exercise mat for all types of workouts.',
      promotion: '',
      price: 22.99,
      status: 'available',
      created_at: Timestamp.fromDate(new Date('2023-06-15')),
      updated_at: Timestamp.fromDate(new Date('2023-07-10')),
      path_to_image: 'path/to/exercise-mat.jpg',
    },
    {
      id: '8',
      name: 'Massage Ball',
      colors: ['Red', 'Black'],
      category: 'Recovery Accessories',
      quantity: 80,
      arrivalTime: '2023-07-30T15:00:00Z',
      brand: 'RecoveryPro',
      origin: 'USA',
      quality: 'High',
      material: 'Silicone',
      description: 'Portable massage ball for trigger point therapy.',
      promotion: 'Free e-book on massage techniques',
      price: 12.49,
      status: 'available',
      created_at: Timestamp.fromDate(new Date('2023-05-25')),
      updated_at: Timestamp.fromDate(new Date('2023-07-01')),
      path_to_image: 'path/to/massage-ball.jpg',
    },
    {
      id: '9',
      name: 'Fitness Tracker',
      colors: ['Black', 'White'],
      category: 'Electronics',
      quantity: 60,
      arrivalTime: '2023-09-10T14:00:00Z',
      brand: 'TechFit',
      origin: 'Japan',
      quality: 'Premium',
      material: 'Plastic',
      description: 'Smart fitness tracker with heart rate monitor.',
      promotion: '20% off for members',
      price: 99.99,
      status: 'available',
      created_at: Timestamp.fromDate(new Date('2023-06-20')),
      updated_at: Timestamp.fromDate(new Date('2023-07-25')),
      path_to_image: 'path/to/fitness-tracker.jpg',
    },
    {
      id: '10',
      name: 'Gym Bag',
      colors: ['Blue', 'Black'],
      category: 'Accessories',
      quantity: 70,
      arrivalTime: '2023-08-15T16:00:00Z',
      brand: 'SportEase',
      origin: 'China',
      quality: 'Standard',
      material: 'Polyester',
      description: 'Spacious gym bag with multiple compartments.',
      promotion: 'Free water bottle included',
      price: 35.99,
      status: 'available',
      created_at: Timestamp.fromDate(new Date('2023-05-30')),
      updated_at: Timestamp.fromDate(new Date('2023-07-10')),
      path_to_image: 'path/to/gym-bag.jpg',
    },
  ];
}
